mysite/mysite/urls.py
# my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView # new

urlpatterns = [
	path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'), 
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
	path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:pollset_id>/vote/', views.vote, name='vote'),
    path('testout/', views.testout, name='testout'),
]

mysite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.conf import settings


class Pollset(models.Model):
    poll_text = models.CharField(max_length=200)
    poll_addtext = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    user_performed = models.ManyToManyField(settings.AUTH_USER_MODEL)
    is_active = models.BooleanField(default=True)
    require_authorization = models.BooleanField(default=True)

    def __str__(self):
        return self.poll_text	
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Question(models.Model):
    question = models.ForeignKey(Pollset, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)

    def __str__(self):
        return self.question_text	

	
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text	
		

mysite/polls/views.py
from django.http import HttpResponseRedirect,HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.core.mail import EmailMessage
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.contrib import messages

from .models import Pollset, Choice, Question

class LoginRequiredMixinSpecial(LoginRequiredMixin):
    def handle_no_permission(self):
        # add custom message
        messages.error(self.request, 'You should log in first')
        return super(LoginRequiredMixinSpecial, self).handle_no_permission()
		
class PermissionRequiredMixinSpecial(PermissionRequiredMixin):
    def handle_no_permission(self):
        # add custom message
        messages.error(self.request, "You don't have permission to view this page. Please log in")
        return HttpResponseRedirect(super(ResultsView, self).get_login_url())

class IndexView(LoginRequiredMixinSpecial,generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_polls_list'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        #Add additional data
        #context['testtext'] = "Test text! It works!!"
        return context
	
    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        #return Pollset.objects.filter(
        #    pub_date__lte=timezone.now()
        #).order_by('-pub_date')[:5]
        return Pollset.objects.filter(
            is_active=True
        ).order_by('-pub_date')[:5]


class DetailView(LoginRequiredMixinSpecial,generic.DetailView):
    
    model = Pollset
    template_name = 'polls/detail.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
		#Extra content
        #context['testtext'] = "Test text! It works!!"
        return context
	
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        #obj = Pollset.objects.filter(pub_date__lte=timezone.now())
        obj = Pollset.objects.filter(is_active=True)
        #for k in obj:
        #    print(k.user_performed.all())
        return obj

class ResultsView(PermissionRequiredMixinSpecial,generic.DetailView):
    model = Pollset
    permission_required = 'polls.view_choice'
    template_name = 'polls/results.html'
    raise_exception = True
    permission_denied_message = 'No permission authorization'
    pollset = get_object_or_404(Pollset, pk=pk)
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        
        #questions_obj_list = pollset.objects.question_set.all()
        return context

	

@login_required
def vote(request, pollset_id):
    pollset = get_object_or_404(Pollset, pk=pollset_id)
	
    questions_obj_list = pollset.question_set.all()
    try:
        #selected_choice = pollset.question_set.get(pk=request.POST["question%s"%])
        selected_choices = {}
        for question in questions_obj_list:
            #selected_choices.append(pollset.question_set.get(pk=request.POST["question%s"%question.id]))
            pk = request.POST["choice%s"%question.id]
            #print("question.id ",question.id)
            #print("pk ",pk)
            selected_choices[question.id] = pk
            #print("question%s"%question.id)
        selected_choices_obj = Choice.objects.filter(pk__in=[v for (k,v) in selected_choices.items()])
        #return HttpResponse([v for (k,v) in selected_choices.items()]) 
    except (KeyError, Choice.DoesNotExist):
        messages.error(request, "You didn't select a choice.")
        return HttpResponseRedirect(reverse('polls:detail',kwargs={'pk':pollset_id}))
        #context = {'pollset': pollset}
        #return render(request, 'polls/detail.html' , context)
    else:
        usr = request.user
        if usr.has_perm('polls.add_choice'):
            if usr not in pollset.user_performed.all():
                for choice in selected_choices_obj:
                    choice.votes += 1
                    choice.save()
                pollset.user_performed.add(usr)
                return HttpResponseRedirect(reverse('polls:results', args=(pollset.id,)))
            else:
                messages.error(request, 'You have already voted!')
                return HttpResponseRedirect(reverse('polls:detail',kwargs={'pk':pollset.id}))
        else:
            messages.error(request, "You don't have permission to vote.... ")
            return HttpResponseRedirect(reverse('polls:detail',kwargs={'pk':pollset.id}))
            # Always return an HttpResponseRedirect after successfully dealing
            # with POST data. This prevents data from being posted twice if a
            # user hits the Back button.
        

@login_required
def testout(request):
    #question = get_object_or_404(Question, pk=pollset_id)

    #return HttpResponse("the answer is %s" % request.user.is_authenticated())

	email = EmailMessage(
	    'Hello',
	    'Body goes here',
	    'anton.tushev@primetals.com',
	    ['anton.tushev@primetals.com'],
	    [],
	    reply_to=['anton.tushev@primetals.com'],
	    headers={'Message-ID': 'foo'},
	)
	email.send()
	
	return HttpResponse(request.user.has_perm('polls.view_choice'))
		
		

mysite/polls/templates/polls/detail.html
{% extends 'base.html' %}
{% block content %}

<section id="c13525" class="main frame-layout frame-layout-0"><div class="container"><div class="frame frame-default frame-type-div "><hr class="ce-div"></div></div></section>
<section class="grid-row frame-layout frame-layout-0">
<div class="container">
<div class="row flexrow">
<div class="col-xs-12 col-md-8">
<section id="c21345" class="main frame-layout frame-layout-0"><div class="container"><div class="frame frame-default frame-type-textpic "><div class="ce-textpic ce-right ce-below"><div class="ce-bodytext">

<h1>{% if request.user in pollset.user_performed.all %}<i class="fas fa-check-circle" style="color:green"></i>{% endif %} {{ pollset.poll_text }}</h1>

{% if pollset.poll_addtext %}<h3>{{ pollset.poll_addtext }}</h3>{% endif %}




{% if messages %}
<hr class="ce-div">
{% for message in messages %}
<div class="select-error"></div><i class="fa"></i><span class="message {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</span>
{% endfor %}
{% endif %}
<hr class="ce-div">
<form action="{% url 'polls:vote' pollset.id %}" method="post">
{% csrf_token %}

{% for question in pollset.question_set.all %}
<h3>{{ forloop.counter }}) {{ question.question_text }}</h3>
<fieldset id="{{ question.id }}">
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice{{ question.id }}" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
</fieldset>
<br/>
{% endfor %}
<input type="submit" value="Vote">
</form>



<p></p>
</div>
</div>
</div>
</div>
</section>
</div>


<div class="col-xs-12 col-md-4">
<p>Publication date: <strong>{{ pollset.pub_date }}</strong></p>
{% if request.user in pollset.user_performed.all %}
<p><i class="fas fa-check-circle" style="color:green"></i> You have voted this poll set</p>
{% else %}
<p style="color:#d9534f"> You haven't voted yet</p>
{% endif %}


<p><a href="{% url 'polls:results' pollset.id %}">Go to results >>></a></p>
 {% if pollset.user_performed.all %}<hr class="ce-div"><p>Voted users:</p><p>

<strong>{% for voted_user in pollset.user_performed.all %}{{ voted_user }} {% endfor %}</strong></p>{% endif %}
</div>

       
</div>
</div>
</section>



{% endblock %}

mysite/polls/templates/polls/index.html
<!-- templates/base.html -->
{% extends 'base.html' %}

{% block content %}

{% if latest_polls_list %}
{% for pollset in latest_polls_list %}
<section id="c13525" class="main frame-layout frame-layout-0"><div class="container"><div class="frame frame-default frame-type-div "><hr class="ce-div"></div></div></section>
<section class="grid-row frame-layout frame-layout-0">
<div class="container">
<div class="row flexrow">
<div class="col-xs-12 col-md-8">
<section id="c21345" class="main frame-layout frame-layout-0"><div class="container"><div class="frame frame-default frame-type-textpic "><div class="ce-textpic ce-right ce-below"><div class="ce-bodytext">
<h2 class="">
<a href="{% url 'polls:detail' pollset.id %}" style="text-decoration:underline">Poll set: {{ pollset.poll_text }}</a>
</h2>
{% if pollset.poll_addtext %}<h3>{{ pollset.poll_addtext }}</h3>{% endif %}
<p><strong>{{ pollset.pub_date }}</strong></p>
{% if pollset.user_performed.all %}<p>Voted users:
<strong>{% for voted_user in pollset.user_performed.all %}{{ voted_user }} {% endfor %}</strong></p>{% endif %}
<p></p>
</div>
</div>
</div>
</div>
</section>
</div>


<div class="col-xs-12 col-md-4">
    <a href="{% url 'polls:results' pollset.id %}"> Go to results >>>> </a>        
</div>

       
</div>
</div>
</section>
{% endfor %}
{% else %}
<section class="grid-row frame-layout frame-layout-0">
<div class="container">
<div class="row flexrow">
<div class="col-xs-12 col-md-8">
<section id="c21345" class="main frame-layout frame-layout-0"><div class="container"><div class="frame frame-default frame-type-textpic "><div class="ce-textpic ce-right ce-below">
<div class="ce-bodytext">
<h3>No polls available</h3>
<p><strong></strong></p>
</div>
</div>
</div>
</div>
</section>
</div>
<!--
<div class="col-xs-12 col-md-4">
            
</div>
-->       
</div>
</div>
</section>
{% endif %}
{% endblock %}

mysite/polls/templates/polls/results.html
{% extends 'base.html' %}
{% block content %}

<section id="c13525" class="main frame-layout frame-layout-0"><div class="container"><div class="frame frame-default frame-type-div "><hr class="ce-div"></div></div></section>
<section class="grid-row frame-layout frame-layout-0">
<div class="container">
<div class="row flexrow">
<div class="col-xs-12 col-md-8">
<section id="c21345" class="main frame-layout frame-layout-0"><div class="container"><div class="frame frame-default frame-type-textpic "><div class="ce-textpic ce-right ce-below"><div class="ce-bodytext">
{{pollset.testtext}}
<h2>Poll result: {{ pollset.poll_text }}</h2>

{% if pollset.poll_addtext %}<h3>{{ pollset.poll_addtext }}</h3>{% endif %}


{% if messages %}
<hr class="ce-div">
{% for message in messages %}
<div class="select-error"></div><i class="fa"></i><span class="message {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</span>
{% endfor %}
{% endif %}

<hr class="ce-div">

{% for question in pollset.question_set.all %}
<h3>{{ forloop.counter }}) {{ question.question_text }}</h3>
{% for choice in question.choice_set.all %}
<p>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</p>
{% endfor %}
<br/>
{% endfor %}

<p></p>
</div>
</div>
</div>
</div>
</section>
</div>


<div class="col-xs-12 col-md-4">
<p>Publication date: <strong>{{ pollset.pub_date }}</strong></p>
{% if request.user in pollset.user_performed.all %}
<p><i class="fas fa-check-circle" style="color:green"></i> You have voted this poll set</p>
{% else %}
<p style="color:#d9534f"> You haven't voted yet</p>
{% endif %}

 {% if pollset.user_performed.all %}<hr class="ce-div"><p>Voted users:</p><p>
<strong>{% for voted_user in pollset.user_performed.all %}{{ voted_user }} {% endfor %}</strong></p>{% endif %}
</div>

       
</div>
</div>
</section>



{% endblock %}

mysite/templates/home.html
<!-- templates/home.html-->
{% extends 'base.html' %}
{% load static %}
{% block content %}


{% if request.resolver_match.view_name == 'home' %}
	<section class="grid-row container-fluid w-1400 subsite-intro frame-layout frame-layout-0 ">
		<div class="col-xs-12 subsite-intro-wrap">
			<div class="container">
				<div class="row flexrow">
					<div class="col-xs-12 col-md-12">
						<section class="grid-row frame-layout frame-layout-0">
							<div class="container">
								<div class="row flexrow">
									<div class="col-xs-12 col-md-9">		
										<section id="c1050" class="main frame-layout frame-layout-0">
										<div class="container">
											<div class="frame frame-default frame-type-text ">
{% else %}
	<section class="grid-row frame-layout frame-layout-0">
		<div class="container">   
			<div class="row flexrow">
				<div class="col-xs-12 col-md-9">
					<section id="c1051" class="main frame-layout frame-layout-0">
						<div class="container">
							<div class="frame frame-default frame-type-header ">
{% endif %}


{% if user.is_authenticated %}
<header>
	<h2 class="">Welcome <strong>{{ user.username }}</strong>! </h2>
	<h3 class="">Thank you for authorization. Use header menu for site navigation and managing your login credentials.</h3>
</header>

<p></p>
{% else %}
<header>
	<h2 class="">About  website</h2>
	<h3 class="">The main purpose of this site is to perform some functions for quick processing of polls, votes, trainings, seminars and other auxiliary company's needs.</h3>
</header>
<p>Use of this site is restricted by authoriation. Please go to the <a href="{% url 'login' %}">login page</a> to get access or <a href="#">contact</a> site administrator.</p>
{% endif %}



{% if request.resolver_match.view_name == 'home' %}
	
											</div>
										</div>
										</section>
									</div>

									<div class="col-xs-12 col-md-3">	
										<section id="c1049" class="main frame-layout frame-layout-0">
											<div class="container">
												<div class="frame frame-default frame-type-image ">
													<div class="ce-image ce-center ce-above">
														<div class="rowce-gallery" data-ce-columns="1" data-ce-images="1">
															<div class="ce-outer">
																<div class="ce-inner">
																	<div class="row ce-row">
																		<div class="ce-column col-xs-12 col-md-12">
																		<figure class="image"><img class="image-embed-item" title="CAREERS" src="{% static 'base/karriere_circle.png' %}" alt="" width="260" height="260"></figure>
																		</div>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
										</section>

									</div>
								</div>
							</div>
						</section>
					</div>
				</div>
			</div>
		</div>
	</section>
{% else %}										
							</div>
						</div>
					</section>
				
				</div>
			
				<div class="col-xs-12 col-md-3">
					
				</div>
			
			</div>
		</div>
	</section>
{% endif %}





{% endblock %}